### ISSUE TITLE
User name in EnterNameComponent not being saved? Possibly not being passed back down

### ISSUE THREAD

**Issue by t-stecker** [aehswill/chutesandladders#16]

**Comment by t-stecker** [comment]
It is being saved, but nothing in the component is being updated so it's grabbing the "old" state from redux. 
I think we can do `const [name, setName]=useState("");` and call that setname between redux dispatch and select- that should trigger the re render.

**Comment by kevinelfert** [comment]
This is good. I just move the api calls to the start page component instead of the EnterNameComponent
